[package]
name = "actix_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-cors = "0.6"
dotenv = "0.15"
reqwest = { version = "0.11", features = ["json"] }
env_logger = "0.9"
log = "0.4"
